/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const PHOTOSHOOT_PROMPTS = [
  // --- ORIGINAL 50 (EYE LEVEL) ---
  "Walking through a sun-drenched Parisian street",
  "Standing in a minimalist art gallery with soft track lighting",
  "Leaning against a sleek black sports car at night in a neon-lit city",
  "Sitting at a rustic wooden table in a cozy, plant-filled cafe",
  "Walking along a windswept beach at golden hour",
  "Standing on a rooftop overlooking a futuristic skyline at dusk",
  "Leaning against a graffiti-covered wall in an urban alleyway",
  "Walking through a serene Japanese garden with cherry blossoms",
  "Standing in a grand library with floor-to-ceiling bookshelves",
  "Sitting on a velvet sofa in a luxurious, dimly lit lounge",
  "Walking through a misty pine forest in the early morning",
  "Standing in a high-tech laboratory with glowing blue interfaces",
  "Leaning against a rustic barn door in a rolling countryside",
  "Walking through a bustling night market with colorful lanterns",
  "Standing in a modern, glass-walled office with a city view",
  "Sitting on a stone bench in a classic Italian piazza",
  "Walking through a field of lavender under a clear blue sky",
  "Standing in a retro 1950s diner with neon signs and chrome",
  "Leaning against a marble column in an ancient Greek temple",
  "Walking through a futuristic space station corridor",
  "Standing in a snowy mountain landscape with a wooden cabin",
  "Sitting on a swing in a whimsical, flower-filled garden",
  "Walking through a desert landscape with dramatic rock formations",
  "Standing in a dark, moody industrial warehouse with light beams",
  "Leaning against a vintage brick building in a historic district",
  "Walking through a vibrant tropical jungle with exotic plants",
  "Standing in a minimalist white studio with dramatic shadows",
  "Sitting at a grand piano in a concert hall with stage lights",
  "Walking through a traditional Moroccan riad with intricate tiles",
  "Standing on a wooden pier over a turquoise lagoon",
  "Leaning against a neon-lit arcade machine in a retro game room",
  "Walking through a field of sunflowers at midday",
  "Standing in a sleek, modern kitchen with marble countertops",
  "Sitting on a park bench in New York's Central Park in autumn",
  "Walking through a futuristic underwater city with glowing domes",
  "Standing in a rustic vineyard in Tuscany at sunset",
  "Leaning against a sleek, metallic wall in a cyberpunk city",
  "Walking through a quiet, cobblestone village in the Cotswolds",
  "Standing in a grand ballroom with crystal chandeliers",
  "Sitting on a colorful rug in a bohemian-style tent",
  "Walking through a high-end luxury boutique with gold accents",
  "Standing in a serene, snow-covered forest at night under the moon",
  "Leaning against a weathered wooden fence in a wild flower meadow",
  "Walking through a bustling airport terminal with large windows",
  "Standing in a modern art museum with abstract sculptures",
  "Sitting at a desk in a cozy, sunlit home office",
  "Walking through a traditional Chinese garden with a koi pond",
  "Standing in a sleek, black-and-white minimalist apartment",
  "Leaning against a colorful surfboard on a tropical beach",
  "Walking through a futuristic botanical garden with bioluminescent plants",

  // --- HIGH ANGLE VARIATIONS (51-100) ---
  "High angle shot from above: Walking through a sun-drenched Parisian street",
  "High angle shot from above: Standing in a minimalist art gallery",
  "High angle shot from above: Leaning against a sleek black sports car",
  "High angle shot from above: Sitting at a rustic wooden table in a cafe",
  "High angle shot from above: Walking along a windswept beach",
  "High angle shot from above: Standing on a rooftop overlooking a skyline",
  "High angle shot from above: Leaning against a graffiti-covered wall",
  "High angle shot from above: Walking through a serene Japanese garden",
  "High angle shot from above: Standing in a grand library",
  "High angle shot from above: Sitting on a velvet sofa in a lounge",
  "High angle shot from above: Walking through a misty pine forest",
  "High angle shot from above: Standing in a high-tech laboratory",
  "High angle shot from above: Leaning against a rustic barn door",
  "High angle shot from above: Walking through a bustling night market",
  "High angle shot from above: Standing in a modern glass-walled office",
  "High angle shot from above: Sitting on a stone bench in a piazza",
  "High angle shot from above: Walking through a field of lavender",
  "High angle shot from above: Standing in a retro 1950s diner",
  "High angle shot from above: Leaning against a marble column in a temple",
  "High angle shot from above: Walking through a space station corridor",
  "High angle shot from above: Standing in a snowy mountain landscape",
  "High angle shot from above: Sitting on a swing in a whimsical garden",
  "High angle shot from above: Walking through a desert landscape",
  "High angle shot from above: Standing in a dark industrial warehouse",
  "High angle shot from above: Leaning against a vintage brick building",
  "High angle shot from above: Walking through a vibrant tropical jungle",
  "High angle shot from above: Standing in a minimalist white studio",
  "High angle shot from above: Sitting at a grand piano in a concert hall",
  "High angle shot from above: Walking through a traditional Moroccan riad",
  "High angle shot from above: Standing on a wooden pier over a lagoon",
  "High angle shot from above: Leaning against a neon-lit arcade machine",
  "High angle shot from above: Walking through a field of sunflowers",
  "High angle shot from above: Standing in a sleek modern kitchen",
  "High angle shot from above: Sitting on a park bench in Central Park",
  "High angle shot from above: Walking through an underwater city",
  "High angle shot from above: Standing in a rustic vineyard in Tuscany",
  "High angle shot from above: Leaning against a metallic wall in a cyberpunk city",
  "High angle shot from above: Walking through a cobblestone village",
  "High angle shot from above: Standing in a grand ballroom",
  "High angle shot from above: Sitting on a colorful rug in a tent",
  "High angle shot from above: Walking through a luxury boutique",
  "High angle shot from above: Standing in a snow-covered forest at night",
  "High angle shot from above: Leaning against a weathered wooden fence",
  "High angle shot from above: Walking through a bustling airport terminal",
  "High angle shot from above: Standing in a modern art museum",
  "High angle shot from above: Sitting at a desk in a sunlit home office",
  "High angle shot from above: Walking through a Chinese garden with a pond",
  "High angle shot from above: Standing in a minimalist apartment",
  "High angle shot from above: Leaning against a surfboard on a beach",
  "High angle shot from above: Walking through a futuristic botanical garden",

  // --- LOW ANGLE VARIATIONS (101-150) ---
  "Low angle shot from below: Walking through a sun-drenched Parisian street",
  "Low angle shot from below: Standing in a minimalist art gallery",
  "Low angle shot from below: Leaning against a sleek black sports car",
  "Low angle shot from below: Sitting at a rustic wooden table in a cafe",
  "Low angle shot from below: Walking along a windswept beach",
  "Low angle shot from below: Standing on a rooftop overlooking a skyline",
  "Low angle shot from below: Leaning against a graffiti-covered wall",
  "Low angle shot from below: Walking through a serene Japanese garden",
  "Low angle shot from below: Standing in a grand library",
  "Low angle shot from below: Sitting on a velvet sofa in a lounge",
  "Low angle shot from below: Walking through a misty pine forest",
  "Low angle shot from below: Standing in a high-tech laboratory",
  "Low angle shot from below: Leaning against a rustic barn door",
  "Low angle shot from below: Walking through a bustling night market",
  "Low angle shot from below: Standing in a modern glass-walled office",
  "Low angle shot from below: Sitting on a stone bench in a piazza",
  "Low angle shot from below: Walking through a field of lavender",
  "Low angle shot from below: Standing in a retro 1950s diner",
  "Low angle shot from below: Leaning against a marble column in a temple",
  "Low angle shot from below: Walking through a space station corridor",
  "Low angle shot from below: Standing in a snowy mountain landscape",
  "Low angle shot from below: Sitting on a swing in a whimsical garden",
  "Low angle shot from below: Walking through a desert landscape",
  "Low angle shot from below: Standing in a dark industrial warehouse",
  "Low angle shot from below: Leaning against a vintage brick building",
  "Low angle shot from below: Walking through a vibrant tropical jungle",
  "Low angle shot from below: Standing in a minimalist white studio",
  "Low angle shot from below: Sitting at a grand piano in a concert hall",
  "Low angle shot from below: Walking through a traditional Moroccan riad",
  "Low angle shot from below: Standing on a wooden pier over a lagoon",
  "Low angle shot from below: Leaning against a neon-lit arcade machine",
  "Low angle shot from below: Walking through a field of sunflowers",
  "Low angle shot from below: Standing in a sleek modern kitchen",
  "Low angle shot from below: Sitting on a park bench in Central Park",
  "Low angle shot from below: Walking through an underwater city",
  "Low angle shot from below: Standing in a rustic vineyard in Tuscany",
  "Low angle shot from below: Leaning against a metallic wall in a cyberpunk city",
  "Low angle shot from below: Walking through a cobblestone village",
  "Low angle shot from below: Standing in a grand ballroom",
  "Low angle shot from below: Sitting on a colorful rug in a tent",
  "Low angle shot from below: Walking through a luxury boutique",
  "Low angle shot from below: Standing in a snow-covered forest at night",
  "Low angle shot from below: Leaning against a weathered wooden fence",
  "Low angle shot from below: Walking through a bustling airport terminal",
  "Low angle shot from below: Standing in a modern art museum",
  "Low angle shot from below: Sitting at a desk in a sunlit home office",
  "Low angle shot from below: Walking through a Chinese garden with a pond",
  "Low angle shot from below: Standing in a minimalist apartment",
  "Low angle shot from below: Leaning against a surfboard on a beach",
  "Low angle shot from below: Walking through a futuristic botanical garden"
];
